"""
ga_pull.py: pull Google Analytics 4 data (read-only) into data/ and write an insights report.

Setup (once): same service account and key as gsc_pull.py (gsc-key.json, or GSC_KEY_FILE in .env).
Cloud runs: no file; the key comes from the GSC_KEY_JSON environment variable (one line).
  1. Google Cloud (same project) → enable "Google Analytics Data API".
  2. GA4 → Admin → Property access management → add the service-account email as **Viewer**.
  3. GA4 → Admin → Property details → copy the numeric Property ID; put GA4_PROPERTY_ID=<id> in .env
     (or pass --property <id>).
  4. pip install google-analytics-data

    python ga_pull.py --check          # confirm access: sessions in the last 7 days
    python ga_pull.py                  # last 90 days → data/ga-<date>-*.csv + data/ga-insights-<date>.md
    python ga_pull.py --days 28
    python ga_pull.py --report-only    # rebuild the report from the latest CSVs (no API call)

Read-only (Viewer role): this script cannot change anything in Google Analytics.
"""

import argparse
import csv
import os
import sys
from datetime import date
from pathlib import Path

DATA = Path("data")
REPORTS = {
    "landing": (["landingPage"], ["sessions", "engagedSessions", "engagementRate", "averageSessionDuration", "keyEvents"]),
    "channels": (["sessionDefaultChannelGroup"], ["sessions", "engagedSessions", "keyEvents"]),
    "sources": (["sessionSource", "sessionMedium"], ["sessions", "engagedSessions"]),
    "outbound": (["linkDomain", "pagePath"], ["eventCount"]),  # enhanced-measurement outbound clicks (affiliate signal)
}


def load_env():
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass


def client():
    try:
        from google.analytics.data_v1beta import BetaAnalyticsDataClient
    except ImportError:
        sys.exit("ERROR: run  pip install google-analytics-data")
    path = Path(os.getenv("GSC_KEY_FILE", "gsc-key.json"))
    if not path.is_file() and os.getenv("GSC_KEY_JSON", "").strip():
        # Cloud runs: the key arrives as one line in the environment, never as a file.
        import json
        return BetaAnalyticsDataClient.from_service_account_info(json.loads(os.environ["GSC_KEY_JSON"]))
    if not path.is_file():
        sys.exit(f"ERROR: key file not found ({path.name}). It is the same key gsc_pull.py uses.")
    return BetaAnalyticsDataClient.from_service_account_file(str(path))


def run(cli, prop, dims, metrics, start, end):
    from google.analytics.data_v1beta.types import (DateRange, Dimension, Filter, FilterExpression, Metric,
                                                    RunReportRequest)
    flt = None
    if "linkDomain" in dims:
        flt = FilterExpression(filter=Filter(field_name="outbound", string_filter=Filter.StringFilter(value="true")))
    rows, offset = [], 0
    while True:
        resp = cli.run_report(RunReportRequest(
            property=f"properties/{prop}", dimensions=[Dimension(name=d) for d in dims],
            metrics=[Metric(name=m) for m in metrics], date_ranges=[DateRange(start_date=start, end_date=end)],
            dimension_filter=flt, limit=10000, offset=offset))
        for r in resp.rows:
            rows.append([v.value for v in r.dimension_values] + [v.value for v in r.metric_values])
        offset += len(resp.rows)
        if not resp.rows or offset >= resp.row_count:
            return rows


def read_csv(path):
    with path.open(encoding="utf-8") as f:
        out = []
        for r in csv.DictReader(f):
            for k, v in r.items():
                try:
                    r[k] = float(v)
                except (TypeError, ValueError):
                    pass
            out.append(r)
        return out


def insights(stamp, window):
    land = read_csv(DATA / f"ga-{stamp}-landing.csv")
    chans = read_csv(DATA / f"ga-{stamp}-channels.csv")
    out_path = DATA / f"ga-{stamp}-outbound.csv"
    outbound = read_csv(out_path) if out_path.exists() else []
    total = sum(r["sessions"] for r in chans) or 1

    L = [f"# 📈 Google Analytics Insights · {stamp}", "",
         f"- **Window:** last {window} days · **Sessions:** {int(total):,} · **Key events:** {int(sum(r['keyEvents'] for r in chans)):,}",
         "- Generated by `ga_pull.py`. Numbers come straight from GA4.", "",
         "## 🚦 Where visitors come from", "", "| Channel | Sessions | Share | Engaged | Key events |", "|---|---|---|---|---|"]
    L += [f"| {r['sessionDefaultChannelGroup']} | {int(r['sessions']):,} | {r['sessions'] / total:.0%} | {int(r['engagedSessions']):,} | {int(r['keyEvents'])} |"
          for r in sorted(chans, key=lambda r: -r["sessions"])]
    L += ["", "## 📄 Top landing pages", "", "| Landing page | Sessions | Engagement rate | Avg time | Key events |", "|---|---|---|---|---|"]
    L += [f"| `{r['landingPage']}` | {int(r['sessions'])} | {r['engagementRate']:.0%} | {r['averageSessionDuration']:.0f}s | {int(r['keyEvents'])} |"
          for r in sorted(land, key=lambda r: -r["sessions"])[:20]]
    weak = [r for r in land if r["sessions"] >= 10 and r["engagementRate"] < 0.4]
    L += ["", "## 🥶 Weak engagement (≥10 sessions, engagement rate < 40%)",
          "Visitors land and leave: check the intro, the quick answer near the top, and page speed.", "",
          "| Landing page | Sessions | Engagement rate |", "|---|---|---|"]
    L += [f"| `{r['landingPage']}` | {int(r['sessions'])} | {r['engagementRate']:.0%} |" for r in sorted(weak, key=lambda r: -r["sessions"])] or ["| none | | |"]
    L += ["", "## 🔗 Outbound clicks by domain (affiliate signal)",
          "Needs GA4 enhanced measurement → Outbound clicks (on by default).", "",
          "| Domain | From page | Clicks |", "|---|---|---|"]
    L += [f"| {r['linkDomain']} | `{r['pagePath']}` | {int(r['eventCount'])} |" for r in sorted(outbound, key=lambda r: -r["eventCount"])[:25]] or ["| none yet | | |"]
    path = DATA / f"ga-insights-{stamp}.md"
    path.write_text("\n".join(L) + "\n", encoding="utf-8")
    return path


def main():
    ap = argparse.ArgumentParser(description="Pull GA4 data (read-only).")
    ap.add_argument("--property")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--days", type=int, default=90)
    ap.add_argument("--report-only", action="store_true")
    a = ap.parse_args()
    load_env()
    DATA.mkdir(exist_ok=True)

    if a.report_only:
        latest = sorted(DATA.glob("ga-*-channels.csv"))
        if not latest:
            sys.exit("No GA CSVs in data/ yet. Run without --report-only first.")
        print(f"✅ Report: {insights(latest[-1].name[3:13], a.days)}")
        return

    prop = a.property or os.getenv("GA4_PROPERTY_ID")
    if not prop or not prop.isdigit():
        sys.exit("ERROR: GA4 property ID missing. Add GA4_PROPERTY_ID=<numbers> to .env or pass --property <numbers>.")
    cli = client()

    if a.check:
        try:
            rows = run(cli, prop, ["sessionDefaultChannelGroup"], ["sessions"], "7daysAgo", "yesterday")
        except Exception as e:  # permission / API-disabled errors come back as exceptions
            sys.exit(f"ERROR: {str(e).splitlines()[0][:300]}\n"
                     "Check: Analytics Data API enabled in Google Cloud, and the service-account email added as Viewer in GA4.")
        print(f"✅ Access OK. Property {prop}: {sum(int(r[1]) for r in rows):,} sessions in the last 7 days.")
        return

    stamp = date.today().isoformat()
    start = f"{a.days}daysAgo"
    print(f"Pulling GA4 property {prop} · last {a.days} days")
    for name, (dims, metrics) in REPORTS.items():
        path = DATA / f"ga-{stamp}-{name}.csv"
        try:
            rows = run(cli, prop, dims, metrics, start, "yesterday")
        except Exception as e:
            print(f"   ⚠️  {name}: skipped ({str(e).splitlines()[0][:150]})")
            continue
        with path.open("w", newline="", encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(dims + metrics)
            w.writerows(rows)
        print(f"   {path}  ({len(rows):,} rows)")
    print(f"✅ Insights: {insights(stamp, a.days)}")


if __name__ == "__main__":
    main()
