"""
gsc_pull.py: pull Google Search Console data (read-only) into data/ and write an insights report.

Setup (once): Google Cloud service account with the Search Console API enabled, added in Search Console as a
"Restricted" user; its JSON key saved as gsc-key.json in this folder (or set GSC_KEY_FILE in .env).
Never print, copy, or commit the key.

    python gsc_pull.py --check              # confirm access: lists the sites the key can read
    python gsc_pull.py                      # pull the last 90 days → data/gsc-<date>-*.csv + data/gsc-insights-<date>.md
    python gsc_pull.py --days 28            # different window
    python gsc_pull.py --report-only        # rebuild the insights report from the latest CSVs (no API call)

Read-only scope (webmasters.readonly): this script cannot change anything in Search Console.
"""

import argparse
import csv
import os
import sys
from datetime import date, timedelta
from pathlib import Path

SITE_CANDIDATES = ["sc-domain:toolpickguide.com", "https://toolpickguide.com/", "https://www.toolpickguide.com/"]
SCOPES = ["https://www.googleapis.com/auth/webmasters.readonly"]
DATA = Path("data")
LAG_DAYS = 3  # Search Console data trails real time by ~2–3 days


def key_file():
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass
    path = Path(os.getenv("GSC_KEY_FILE", "gsc-key.json"))
    if not path.is_file():
        sys.exit(f"ERROR: key file not found ({path.name}). Save the service-account JSON as gsc-key.json in this folder.")
    return path


def service():
    try:
        from google.oauth2 import service_account
        from googleapiclient.discovery import build
    except ImportError:
        sys.exit("ERROR: run  pip install google-api-python-client google-auth")
    creds = service_account.Credentials.from_service_account_file(str(key_file()), scopes=SCOPES)
    return build("searchconsole", "v1", credentials=creds, cache_discovery=False)


def pick_site(svc):
    sites = [s["siteUrl"] for s in svc.sites().list().execute().get("siteEntry", [])]
    if not sites:
        sys.exit("No sites visible. In Search Console → Settings → Users and permissions, add the service account email (Restricted).")
    for c in SITE_CANDIDATES:
        if c in sites:
            return c, sites
    return sites[0], sites


def query(svc, site, start, end, dims, limit=25000):
    rows, start_row = [], 0
    while True:
        body = {"startDate": start, "endDate": end, "dimensions": dims, "rowLimit": limit, "startRow": start_row}
        batch = svc.searchanalytics().query(siteUrl=site, body=body).execute().get("rows", [])
        rows += batch
        if len(batch) < limit:
            return rows
        start_row += limit


def write_csv(path, dims, rows):
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(dims + ["clicks", "impressions", "ctr", "position"])
        for r in rows:
            w.writerow(r["keys"] + [int(r["clicks"]), int(r["impressions"]), round(r["ctr"], 4), round(r["position"], 1)])


def read_csv(path):
    with path.open(encoding="utf-8") as f:
        out = []
        for r in csv.DictReader(f):
            for k in ("clicks", "impressions"):
                r[k] = int(r[k])
            r["ctr"], r["position"] = float(r["ctr"]), float(r["position"])
            out.append(r)
        return out


def insights(stamp, window):
    qp = read_csv(DATA / f"gsc-{stamp}-query_page.csv")
    queries = read_csv(DATA / f"gsc-{stamp}-queries.csv")
    pages = read_csv(DATA / f"gsc-{stamp}-pages.csv")
    total_clicks = sum(r["clicks"] for r in pages)
    total_impr = sum(r["impressions"] for r in pages)

    striking = sorted([r for r in qp if 8 <= r["position"] <= 20 and r["impressions"] >= 20],
                      key=lambda r: -r["impressions"])[:25]
    low_ctr = sorted([r for r in queries if r["position"] <= 10 and r["impressions"] >= 50 and r["ctr"] < 0.02],
                     key=lambda r: -r["impressions"])[:15]
    top_pages = sorted(pages, key=lambda r: -r["clicks"])[:15]
    no_clicks = sorted([r for r in pages if r["clicks"] == 0 and r["impressions"] >= 50], key=lambda r: -r["impressions"])[:15]

    short = lambda u: u.replace("https://toolpickguide.com", "") or "/"  # noqa: E731
    L = [f"# 🔎 Search Console Insights · {stamp}", "",
         f"- **Window:** last {window} days (data trails ~{LAG_DAYS} days) · **Clicks:** {total_clicks:,} · **Impressions:** {total_impr:,}",
         "- Generated by `gsc_pull.py`. Numbers come straight from Search Console.", "",
         "## 🎯 Striking distance (position 8–20, ≥20 impressions)",
         "These rank just off page 1. Small on-page work (title, H2, internal links) can move them up.", "",
         "| Query | Page | Impr. | Clicks | Avg pos |", "|---|---|---|---|---|"]
    L += [f"| {r['query']} | `{short(r['page'])}` | {r['impressions']:,} | {r['clicks']} | {r['position']} |" for r in striking] or ["| none yet | | | | |"]
    L += ["", "## ✏️ Low CTR on page 1 (pos ≤10, ≥50 impressions, CTR < 2%)",
          "Seen but not clicked: usually the SEO title or meta description needs work.", "",
          "| Query | Impr. | CTR | Avg pos |", "|---|---|---|---|"]
    L += [f"| {r['query']} | {r['impressions']:,} | {r['ctr']:.1%} | {r['position']} |" for r in low_ctr] or ["| none yet | | | |"]
    L += ["", "## 📄 Top pages by clicks", "", "| Page | Clicks | Impr. | CTR | Avg pos |", "|---|---|---|---|---|"]
    L += [f"| `{short(r['page'])}` | {r['clicks']} | {r['impressions']:,} | {r['ctr']:.1%} | {r['position']} |" for r in top_pages]
    L += ["", "## 👻 Pages with impressions but zero clicks (≥50 impressions)", "", "| Page | Impr. | Avg pos |", "|---|---|---|"]
    L += [f"| `{short(r['page'])}` | {r['impressions']:,} | {r['position']} |" for r in no_clicks] or ["| none | | |"]
    out = DATA / f"gsc-insights-{stamp}.md"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    return out, len(striking), len(low_ctr)


def main():
    ap = argparse.ArgumentParser(description="Pull Search Console data (read-only).")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--days", type=int, default=90)
    ap.add_argument("--report-only", action="store_true")
    a = ap.parse_args()
    DATA.mkdir(exist_ok=True)

    if a.report_only:
        latest = sorted(DATA.glob("gsc-*-queries.csv"))
        if not latest:
            sys.exit("No CSVs in data/ yet. Run without --report-only first.")
        stamp = latest[-1].name[4:14]
        out, s, c = insights(stamp, a.days)
        print(f"✅ Report: {out}  ({s} striking-distance, {c} low-CTR)")
        return

    svc = service()
    site, sites = pick_site(svc)
    if a.check:
        print("✅ Access OK. Sites this key can read:")
        for s in sites:
            print(f"   {'→' if s == site else ' '} {s}")
        return

    end = date.today() - timedelta(days=LAG_DAYS)
    start = end - timedelta(days=a.days - 1)
    stamp = date.today().isoformat()
    print(f"Pulling {site} · {start} → {end}")
    for name, dims in (("queries", ["query"]), ("pages", ["page"]), ("query_page", ["query", "page"])):
        rows = query(svc, site, start.isoformat(), end.isoformat(), dims)
        path = DATA / f"gsc-{stamp}-{name}.csv"
        write_csv(path, dims, rows)
        print(f"   {path}  ({len(rows):,} rows)")
    out, s, c = insights(stamp, a.days)
    print(f"✅ Insights: {out}  ({s} striking-distance, {c} low-CTR)")


if __name__ == "__main__":
    main()
